/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.estruturados.encadeados;

public class App {

    public static void main(String[] args) {
        ListaEncadeada teste = new ListaEncadeada();
        teste.insere(1);
        teste.insere(2);
        teste.insere(3);
        teste.insere(4);
        teste.insere(5);
        teste.insere(6);
        System.out.println(teste.pegar(99));
    }
}
