/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.estruturados.encadeados;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
